### ISSUE TITLE
Problem checking if a point is inside a Shape

### ISSUE THREAD

**Issue by lorisbel** [locationtech/spatial4j#100]
Hi, I'm a newbie in using spatial4j. I created a Shape that refers to Spagna square in Rome:

POLYGON ((12.481795102357864 41.90594219388104, 12.48123 41.906501, 12.481986 41.90666, 12.48234 41.90674, 12.482990026473999 41.906938296574225, 12.483067810535431 41.90682251790111, 12.48347282409668 41.906341435303666, 12.483869791030884 41.90585236421689, 12.482727 41.905173, 12.482585 41.905151, 12.482359 41.905383, 12.481795102357864 41.90594219388104))

I need to check if a given point is contained or not by this shape. So I use the code:

final static SpatialContext ctx = SpatialContext.GEO;
PointImpl p = new PointImpl(12.48402, 41.905759, ctx);
if (container.relate(inner) == SpatialRelation.CONTAINS) return true;
else return false;

I get "false", but the correct result should be "true".
Can somebody help me?
Thanks in advance.

**Comment by dsmiley** [comment]
Hi.
I believe the correct answer is false.  Notice that 12.484 is greater than all the 'X' values in the point list.  Why do you think it should be true?
P.S. consider this tool to experiment: http://arthur-e.github.io/Wicket/sandbox-gmaps3.html
