### ISSUE TITLE
Distance units

### ISSUE THREAD

**Issue by hypexr** [locationtech/spatial4j#116]
Hi, what are the units for the distance results?

**Comment by dsmiley** [comment]
For spherical (e.g. "isGeo() == true") it is degrees -- there are 360 of them going completely around the surface of a sphere.  When not geo, it's a flat plane and the units are implied by the data given; they aren't specified by Spatial4j.

**Comment by hypexr** [comment]
Thanks!  I'm using the GEO spatial context and isGeo() does return true.  I'm feeding in 2 points calcDistance() that I created from GPS latitude and longitudes. Does spatial4j provide a way to get meters from the degrees for the earth?

**Comment by dsmiley** [comment]
Yes; see DistanceUtils.DEG_TO_KM — a multiplier to multiply degrees to get
to kilometers.

On Wed, Aug 26, 2015 at 4:55 PM Scott Rippee <notifications@github.com>
wrote:

> Thanks! I'm using the GEO spatial context and isGeo() does return true.
> I'm feeding in 2 points calcDistance() that I created from GPS latitude and
> longitudes. Does spatial4j provide a way to get meters from the degrees for
> the earth?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locationtech/spatial4j/issues/116#issuecomment-135167955>
> .
>
-- 
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com

**Comment by hypexr** [comment]
Works great. Thanks.  Sorry I keep posting on this same message.. Is there a way to check if a circle is within range of a point?  I have a point with an accuracy (creates the circle) and I want to know if it's with an acceptable distance of a point.

**Comment by dsmiley** [comment]
circleOrWhateverShape.relate(ctx.makePoint(x,y)).intersects()

On Thu, Aug 27, 2015 at 4:22 PM Scott Rippee <notifications@github.com>
wrote:

> Works great. Thanks. Sorry I keep posting on this same message.. Is there
> a way to check if a circle is within range of a point? I have a point with
> an accuracy (creates the circle) and I want to know if it's with an
> acceptable distance of a point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locationtech/spatial4j/issues/116#issuecomment-135542529>
> .
>
-- 
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com

**Comment by hypexr** [comment]
For my case the circle will not intersect with the point, but it will be a certain distance away from the point.    That distance is what I want to know.

**Comment by dsmiley** [comment]
Okay well that’s just calculating the distance between two points then.
Call SpatialContext.GEO.getDistCalc().distance(…)

On Thu, Aug 27, 2015 at 5:25 PM Scott Rippee <notifications@github.com>
wrote:

> For my case the circle will not intersect with the point, but it will be a
> certain distance away from the point. That distance is what I want to know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locationtech/spatial4j/issues/116#issuecomment-135558592>
> .
>
-- 
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com

**Comment by hypexr** [comment]
But I don't know what the closest edge of the circle is to the point.  For example:
   ___
 /         \
|     .      | 1                                                     . 2
 \          /
    -----

I want to know the distance between 1 and 2.  But I will not know which side of the circle. the point will be closest to.

**Comment by dsmiley** [comment]
I’m not sure I understand what you mean by the “side” of a circle — it has
a continuous boundary… not sure I’d call it a “side” but perhaps we are
thinking of the same thing.  The ASCII art is not perfectly clear but I’ll
guess as what your question is, in my words.  Do you want to calculate the
distance between a point and the boundary of the circle?  To do that simply
compute the distance between the center of the circle and this point and
then subtracting the radius of the circle from it.

On Fri, Aug 28, 2015 at 4:30 PM Scott Rippee <notifications@github.com>
wrote:

> But I don't know what the closest edge of the circle is to the point. For
> example:
> ------------------------------
>
> / \
> | . | 1 . 2
> \ /
> -----
>
> I want to know the distance between 1 and 2. But I will not know which
> side of the circle. the point will be closest to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/locationtech/spatial4j/issues/116#issuecomment-135881354>
> .
>
-- 
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com

**Comment by hypexr** [comment]
Of course!  Thanks
