### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by dsmiley** [locationtech/spatial4j#132]
See https://locationtech.org/wiki/Project_Checklist "Contribution Guide" section.  

Additional things to mention:
* Code style -- loosely as Google's Java style
* Run: `git fetch origin refs/replace/*:refs/replace/*`
* Remember the "-s" git flag (not required by Committers)
* Link to this from README.md

Care to take a stab at this @jdeolive ?

**Comment by jdeolive** [comment]
@dsmiley Sure thing, I'll take a crack at this either today or early tomorrow.
