### ISSUE TITLE
.6 Release in Maven?

### ISSUE THREAD

**Issue by bisoldi** [locationtech/spatial4j#136]
Will .6 Release be distributed to Maven Central?  It doesn't look like it's there yet.

Also, will Github be upgraded to .6-RELEASE instead of SNAPSHOT?

Thanks!

**Comment by dsmiley** [comment]
It's happening within the next 24 hours.  I'm getting through some new release procedures.

**Comment by bisoldi** [comment]
Awesome, thank you!

**Comment by dsmiley** [comment]
I released 0.6 to maven-central just now.  I think it syncs within a couple hours tops.
