### ISSUE TITLE
Create circle using centroid and radius in miles/km

### ISSUE THREAD

**Issue by bisoldi** [locationtech/spatial4j#139]
I've been looking and don't see any methods within Spatial4j to solve this.  I'd like to be able to create a circle (and other shapes) based on radius expressed in distance (i.e. miles, kilometers, etc.).

So, with a Circle, I can create a circle with a centroid and radius, though the Javadoc says the radius must be in the same unit of distance as x, y (e.g. Degrees).  For a geospatial application, it would be helpful to be able to express radius in more "human readable" ways.

Is there a method already in the library that I'm missing or any willingness to implement one?

Thanks!

**Comment by varsis** [comment]
I think what you are looking for is DistanceUtils. It has all sorts of functions/ constants to convert from radians or degrees to km/miles 

https://github.com/locationtech/spatial4j/blob/master/src/main/java/org/locationtech/spatial4j/distance/DistanceUtils.java

**Comment by bisoldi** [comment]
Yep, feel dumb now.  Correct me if I'm wrong...What I'm looking for 

public static double dist2Degrees(double dist, double radius)

and I would use EARTH_MEAN_RADIUS_MI or EARTH_EQUATORIAL_RADIUS_MI (assuming I wanted to express in miles) as the radius parameter.

**Comment by deepakgupta1290** [comment]
Could someone let me know if how to create circle with radius in nautical miles and center point.?

**Comment by dsmiley** [comment]
First, you always need a SpatialContext; perhaps use SpatialContext.GEO.  Them grab the ShapeFactory from there, after which you can call a method that creates a circle.  It asks for a radius in decimal degrees.  You need to do the conversion.  Google whatever the constant multiplier is for nautical miles to something else like kilometers, and then with the info above you should be able to figure it out.
