### ISSUE TITLE
Confusion and possible issue around JtsSpatialContext conversion for dateline-crossing geometries

### ISSUE THREAD

**Issue by worace** [locationtech/spatial4j#150]
Hi there -

I'm hoping to get some guidance on a strange behavior I ran into today. I've been working to update the dependencies for a geospatial library we have at factual (https://github.com/Factual/geo) to the latest JTS and spatial4j versions. Along the way I ran into an issue where JTS geometries which cross the dateline and are converted to Spatial4J shapes get converted successfully the first time, but not on successive attempts.

It's maybe a little easier to show than to explain so I made an example project which demonstrates the issue I'm seeing here: https://github.com/worace/Spatial4JExample.

I'm not sure if this is a bug in either Spatial4J or JTS, or if it's known behavior and I'm simply using one of the classes wrong.

Interestingly I did notice that the test case in Spatial4J includes a `clone` of the geometry before converting, so perhaps this is a known issue? (https://github.com/locationtech/spatial4j/blob/master/src/test/java/org/locationtech/spatial4j/context/jts/JtsSpatialContextTest.java#L29)

If that's the recommended approach we could do the same, although I hate to incur the performance penalty of cloning things all the time if we don't have to.

Fiinally, along the lines of this issue: https://github.com/locationtech/spatial4j/issues/137, when I upgraded our dependencies I noticed those methods are marked as deprecated now. I'm wondering if there's any info somewhere on what the replacement is and how it should be used?

Thanks for your work on this library! Let me know if I can give any more context to explain this issue.

**Comment by dsmiley** [comment]
Hello Horace, nice to meet you.

I think this is either:
(A) an under-documented gotcha of Spatial4j's JtsSpatialContext.makeShape().  The passed in JTS geometry will in fact be modified if it crosses the dateline.
(B) A bug in Spatial4j's JtsGeometry code, where arguably it ought to not modify it's input JTS Geometry instance.  It will do this if it crosses the dateline.

Given dateline crosses are not particularly common, I lean towards fixing (B).

**Comment by dsmiley** [comment]
In the mean time you could conditionally clone your polygon if `geom.getEnvelopeInternal().getWidth() >= 180`

The fix: JtsGeometry.unwrapDateline(Geometry) could be made to return either current or cloned Geometry instead of integer crossings; the caller doesn't currently use the response.

**Comment by worace** [comment]
@dsmiley thanks for this informative response!

I didn't know about the `getEnvelopeInternal` option for checking the width; that would definitely be a big improvement to my current clone-everything workaround, so I'll probably use that in the immediate term.

I'll try to familiarize myself more with the `unwrapDateline` method you mention as well.
