### ISSUE TITLE
Non-complient Notice for License

### ISSUE THREAD

**Issue by jkamenik** [locationtech/spatial4j#157]
Your README states that the software License is ASL, but the notice.md is the Eclipse Public License.  If the license is ASL then the notice should adhere to the license requirements; namely "Copyright (c) <year> <author>" instead of being a different license.

**Comment by dsmiley** [comment]
Thanks for bringing this to my attention.  I will bring it up with the Eclipse Management Organization, who helps with IP policy.  I recall I was told that the notice needs to be as such, even though it's licensed differently than what the notice suggests.  Yeah confusing.  IMO (which doesn't matter as IANAL) what is currently notice.md wouldn't even be that, it'd be a document named after it's heading "user-agreement.md".  Perhaps some explanatory info in the beginning of the file would clarify the ambiguities between the boilerplate with the realities.
Any way, stay tuned.

**Comment by waynebeaton** [comment]
LocationTech Spatial4J has been around long enough that we were still requiring the Eclipse SUA as a notice. Strictly speaking, the SUA was (and is) required for projects that are generating Eclipse Platform Plug-ins and Features, and is really a poor fit for just about everything else.

It took us a while, but we've updated this and rolled out some new documentation. I thought that we'd hit most of the communication channels, but we must have missed yours. My apologies for that oversight.

https://www.eclipse.org/projects/handbook/#legaldoc-notice

We've been working on an experimental documentation generator that seems to do a decent job for Spatial4J. I'm pretty sure that you can just grab the NOTICE content from there.

https://www.eclipse.org/projects/tools/about.php?id=locationtech.spatial4j

Note that I'm pretty sure that you don't have to update any file headers (there's several different versions of correct, the new-ish one that we're showing in the documentation and generator is just our latest refinement).

**Comment by dsmiley** [comment]
Fantastic @waynebeaton ; I'm happy to see that we can ditch the current notice.md, which I've found to have ridiculous content as Spatial4j is not an Eclipse plugin.

I'm curious about the "Third Party Content" portion.  This is effectively Spatial4j's dependencies.  Spatial4j only has "works-with" dependencies -- which is to say all dependencies are either of a build/test nature (no runtime), or are associated with an "optional" feature.  The auto-generated notice only chose "jackson-databind" (which is for an "optional" feature).  There are two additional dependencies for "optional" features (the pom.xml makes it easy to see which dependencies are used how).  Furthermore, jackson-databind also brings along its own transitive dependencies (jackson-core, jackson-annotations) but these aren't listed in pom.xml; maven takes care of the transitive loading.  What is the policy on this?

**Comment by waynebeaton** [comment]
The generator pulls information out of IPZilla. It looks like CQ 11094 is added because it is incorrectly categorized as a prerequisite. I see that you've already asked the IP Team to recategorize it; I'll follow up with Sharon.

In the meantime, you can just modify the generated content (which is intended as a template).

More generally, you don't need CQs for transitive dependencies of "works with" CQs. For completeness, you do require CQs for transitive dependencies of prerequisites
