### ISSUE TITLE
Wrong Circle BoundingBox?

### ISSUE THREAD

**Issue by MoeweX** [locationtech/spatial4j#170]
Hi, I try to get the bounding box of a circle, and I think it is not correct. 
This code
```
JtsSpatialContext ctx = JtsSpatialContext.GEO;
Point p = ctx.getShapeFactory().pointLatLon(39.984702, 116.318417);
Shape circle = ctx.getShapeFactory().circle(p, 0.1);
logger.info(circle);
logger.info(circle.getBoundingBox());
```
produces the following output:
```
Circle(Pt(x=116.318417,y=39.984702), d=0.1° 11.12km)
Rect(minX=116.18790545960631,maxX=116.44892854039368,minY=39.884702,maxY=40.084702)
```
While minY and maxY are as I would expect them to be, I am confused by minX and maxX.
For minX, I would like to have seen 116.218417, and for maxX, I would like to have seen 116.418417.
Am I missing something?

**Comment by dsmiley** [comment]
With a debugger ensure that this method gets called: https://github.com/locationtech/spatial4j/blob/aa5fb728509ec74b28162142b1dd1a0fad88ba27/src/main/java/org/locationtech/spatial4j/distance/DistanceUtils.java#L291
Assuming it does, this code does the calculation and includes a URL to the origins of the calculation: 
http://gis.stackexchange.com/questions/19221/find-tangent-point-on-circle-furthest-east-or-west

**Comment by MoeweX** [comment]
Alright, the method is called. So everything works as expected and the values are correct for a sphere?

**Comment by dsmiley** [comment]
Yes.  I looked through the tests in hopes of finding something that provided the bounding box is minimal but turned up nothing :-/. I can imagine how to do this by taking the bounding box, shrinking it slightly, and systematically looking for points on the edges that intersect with the original circle.  Eventually a point should be found.  For another day I guess.

**Comment by MoeweX** [comment]
That's sounds like a good approach to validate the bounding box dimensions 👍
