### ISSUE TITLE
Unable to create Polygon giving exception Unsupported shape

### ISSUE THREAD

**Issue by anjan-vassarlabs** [locationtech/spatial4j#171]
SpatialContext ctx = SpatialContext.GEO;
		SpatialContextFactory spa =new  SpatialContextFactory();
		WKTReader wtr = new WKTReader(ctx,spa);

			wtr.parse("POLYGON((-125.22656679154 49.089853763581, -123.99609804154 46.453135013581, -123.99609804154 44.343760013581 , -129.22656679154 49.089853763581))");

I'm able to get point and Linestrin g etc.. but polygon is throwing exception

**Comment by dsmiley** [comment]
Tip: when reporting that an exception is thrown, be more specific than that -- especially the class & message.

`java.text.ParseException: java.lang.UnsupportedOperationException: Unsupported shape of this SpatialContext. Try JTS or Geo3D.`

The default SpatialContext does not support polygons.  There is a JtsSpatialContext.GEO which will work.  Over in Apache Lucene spatial-extras there is a Geo3D spatial context.
