### ISSUE TITLE
Publish spatial4j-0.8 to Maven Central

### ISSUE THREAD

**Issue by guyisra** [locationtech/spatial4j#174]
0.8 isn't release yet and it solves several issues

@hmottestad please release the jar so we can use it instead of compiling on our own

thanks

**Comment by hmottestad** [comment]
I’m not the author of this library.

**Comment by dsmiley** [comment]
I will do so within the next month or so any existing WIP settles.  If I take too long, just remind me.

**Comment by jsa34ito** [comment]
Hello!  I was wondering if there was any news about releasing 0.8 to Maven Central?  If there are any blockers / work that needs to be done pre-publishing, I can help have a look (can't promise but willing to have a stab!)

**Comment by dsmiley** [comment]
I've been dragging my feet; thanks for bringing this to the top (or near top) of my TODO list

**Comment by dsmiley** [comment]
FYI Release 0.8 is pending...https://projects.eclipse.org/projects/locationtech.spatial4j/releases/0.8You can try out v0.8 SNAPSHOT here: https://oss.sonatype.org/content/repositories/snapshots/org/locationtech/spatial4j/spatial4j/0.8-SNAPSHOT/

**Comment by dsmiley** [comment]
0.8 was released!

**Comment by hmottestad** [comment]
Thank you @dsmiley
