### ISSUE TITLE
THIS PROJECT MAY BE DEAD

### ISSUE THREAD

**Issue by icemagno** [locationtech/spatial4j#176]
Seems this project is dead.

**Comment by dsmiley** [comment]
It does what it needs to do.  If there's a major problem you have to report then I'll take it seriously, but I confess my attention is elsewhere these days.  @jdeolive how about you?

**Comment by dsmiley** [comment]
BTW due to an email filtering problem on my end, I became blind to some issues reported here over the past year.  I'll take a look at them soon.

**Comment by jdeolive** [comment]
@dsmiley Yeah I wish I had time to devote to open source efforts but unfortunately unless it's fixing a bug or making an improvement for one of my "day job" projects, I generally don't have the time to contribute. But always happy to do a quick pull request review, etc... for people that have more capacity to contribute.

**Comment by dsmiley** [comment]
I'll re-open; I don't want to hide this by closing it.

**Comment by dsmiley** [comment]
Just had a new release... not really a dead project.
