### ISSUE TITLE
Getting incorrect distance between two Lat-long

### ISSUE THREAD

**Issue by fatichar** [locationtech/spatial4j#185]
Consider following code. I am getting smaller than expected  distance  between two points on the Earth.

```
    SpatialContext spatial = SpatialContext.GEO;

    var point1 = new PointImpl(37.32242202758789, -121.9046859741211, spatial);
    var point2 = new PointImpl(37.33733367919922, -121.89395141601562, spatial);

    var distanceInDegrees = spatial.calcDistance(point1, point2);
    var distanceInMeters = distanceInDegrees * DistanceUtils.DEG_TO_KM * 1000;
```

This gives me ```distanceInMeters = 1480.69```, whereas, following online distance calculators give the value as 1910 meters (as does Google map). 

- http://www.meridianoutpost.com/resources/etools/calculators/calculator-latitude-longitude-distance.php?
- https://gps-coordinates.org/distance-between-coordinates.php

**Comment by fatichar** [comment]
Problem was: I used latitude as 'x' and longitude as 'y' while creating PointImpl objects.

**Comment by dsmiley** [comment]
Happens all the time :-)
