### ISSUE TITLE
java.lang.NoSuchMethodError: org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LineString;

### ISSUE THREAD

**Issue by mikes360** [locationtech/spatial4j#192]
When I do a SpatialPredicate.Intersects between a GeoCircle and Polygon created from the JtsShapeFactory I get an error. 

The error is a cast error on line 276 of JtsGeometry. 

SpatialRelation rel = relateEnclosedRing((LinearRing) polygon.getExteriorRing());

I have read the comments about this being a tricky areas of the code but dont know what else I should do when I want to test a circle intersects a polygon. 

Thanks,
Mike

**Comment by dsmiley** [comment]
Exactly which version of Spatial4J and JTS are you using?

**Comment by mikes360** [comment]
I am using version 0.7

**Comment by dsmiley** [comment]
And JTS?  A java.lang.NoSuchMethodError suggests a versioning issue with JTS.  Can you provide the full stack trace as well?

**Comment by seanmalter** [comment]
I'm also having this issue. 

Stacktrace:
![image](https://user-images.githubusercontent.com/25463724/115450183-739ef980-a1d0-11eb-8620-35c5f940bf48.png)

Mvn Dependencies:
        
        <dependency>
            <groupId>org.locationtech.spatial4j</groupId>
            <artifactId>spatial4j</artifactId>
            <version>0.7</version>
        </dependency>
        
        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.17.0</version>
        </dependency>

Could it be related to JTS or Spatial4J?

**Comment by seanmalter** [comment]
Fixed by updating dependencies:
```
        <!-- https://mvnrepository.com/artifact/org.locationtech.spatial4j/spatial4j -->
        <dependency>
            <groupId>org.locationtech.spatial4j</groupId>
            <artifactId>spatial4j</artifactId>
            <version>0.8</version>
        </dependency>
        <!-- JTS is essentially only used for polygons. -->
        <!-- https://mvnrepository.com/artifact/org.locationtech.jts/jts-core -->
        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.18.1</version>
        </dependency>
```

**Comment by dsmiley** [comment]
Glad this was figured out.
