### ISSUE TITLE
Support JTS 18.1

### ISSUE THREAD

**Issue by GisMarsch** [locationtech/spatial4j#205]
Hello,

We are using Lucene and Geotools in our application and tried to update to a newer Geotools version.
Now our tests in lucene fail, because of spatial4j dependency. Geotools is now using JTS 18.1 and there is an incompatibility compared to JTS 17.0 in spatial4j.
The InStream in `org.locationtech.spatial4j.io.jts.JtsBinaryCodec.readJtsGeom(DataInput)` has now a return type int instead of void.

This should be an easy fix, I will try to provide a PullRequest for that.

**Comment by janhoy** [comment]
Merged manually, can be closed @dsmiley
