### ISSUE TITLE
Reverse Geocoding

### ISSUE THREAD

**Issue by azzahrah** [locationtech/spatial4j#208]
i have mysql spatial data, geometry (Point, Polygon, and LineString), is possible convert to spatial4j and build reverse geocoding?, mybe any example howto import from mysql, and indexed imported data and reverse based on latitude/longitude?

**Comment by dsmiley** [comment]
Hi.  No, Spatial4j doesn't hold many shapes in an index that can be queried like that.  I've done this with Apache Solr.  If your data can entirely fit in RAM, then I suggest looking at JTS SpatialIndex.
